project_name: timeshift
build:
  main: timeshift.go
  binary: timeshift
  env:
    - CGO_ENABLED=1
  goos:
    - windows
  goarch:
    - amd64
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: zip
  wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_windows_checksums.txt"
release:
  draft: true

